# Generated by Django 4.2.4 on 2023-08-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='measurement',
            field=models.ManyToManyField(blank=True, to='measurement.measurement'),
        ),
    ]
